import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[window]
opacity = 0.95
padding.x = 5
padding.y = 5

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"
